server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/MovieAppMvcDb"
    username: "postgres"
    password: "*****"
  jpa:
    hibernate:
      ddl-auto: update
